import { Inter, Html, Head, Main, NextScript, GoogleFont } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
<div className="text-center text-xl font-bold text-gray-800">
        Welcome to the Next.js Home Page!
      </div>
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
